# Site settings
title: 영비의 블로그
url: "http://rla0ql.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "/" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Asia/Seoul
description: >
  description

# Your information
email: rla0ql@daum.net
author: 김영비
# avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
avatar: "//github.com/yunho0130/yunho0130.github.io/blob/master/_jpg/yunhomaeng.png"
profile: <br> 경영 빅데이터 복습 블로그
#twitter_username: twitter_username
github_username:  rla0ql

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: 0bee   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji
 - jekyll-sitemap

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
